# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e467c8a8ce0fc3640677985efd8825f6112709e0f3c12447c8c70f357622072e1bab2b0d0a35092a33b945407172a12d4335d1a41b42c730b186e1833a398158

test:
  secret_key_base: b9ad111f225f7e3147cf0426bfafee0a9b4153f913b57223f95236793bd8a28b86715704d758cd6f198edf41b183e76685e387afbe6b38e0b2c38e2cd415277c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
